feat(wip): Use pingora_runtime for handle
Below error must be resolved:

```
thread 'main' panicked at /Users/lee/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pingora-core-0.3.0/src/server/mod.rs:328:57:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    4282 abort      cargo run
```